services:
  - type: web
    name: news-scrapper
    env: python
    plan: free
    rootDir: backend

    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-tam tesseract-ocr-eng
      pip install -r requirements.txt
      playwright install chromium --with-deps

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
      - key: TESSDATA_PREFIX
        value: "/usr/share/tesseract-ocr/4.00/tessdata"
      - key: OCR_SPACE_API_KEY
        sync: false
